### ISSUE TITLE
Utfälld meny fälls ihop (men bakgrunden fortfarande mörkad) när man byter från "mobil -> desktop" eller "dekstop -> mobil".

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#103]
# User story
Som användare vill jag att menyn fortsätter vara utfälld om jag skalar om fönstret när jag har menyn öppen. 

# Acceptanskriterier

- [ ] Menyn fortsätter antingen vara utfälld när man skalar förbi våra breakpoints eller också så fälls den ihop och bakgrunden upphör vara nedmörkad. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Denna borde lösa sig med den nya navigationen. @regionhallandviktor När du är tillbaka från semestern så kan du titta på skisserna, där finns ingen utfälld meny längre. Om det är ok att gå på det förslaget så kan vi ju stänga denna issue.

**Comment by regionhallandviktor** [comment]
Stänger denna då den hör till gammal version
