### ISSUE TITLE
Som besökare vill jag se bilder i förhållande till text på ett korrekt sätt

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#106]
# Acceptanskriterier

- [ ] Om redaktören har placerat bilden till vänster om texten så ska detta visas på samma sätt för besökaren som det gör för redaktören.

Titta t ex på sidan http://vardgivare.regionhalland.se/behandlingsstod/lakemedel/publikationer-och-nyhetsbrev-om-lakemedel/. Bilden där är satt att ligga till vänster om texten, men inte all text visas på samma sätt för besökaren som den gör för redaktören.

För besökare
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/80a13895-e940-4767-8fdb-3b590d13dc74)

För redaktörer
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/f6911498-6150-485c-9b47-8979d252e1bf)

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Vi behöver diskutera hur man bäst löser det här. TinyMCE skapar kod som kort sagt är skräp (massor med inline styling, tomma h2 osv) och inte är medveten om hur styleguiden gör saker. Den kod som TinyMCE genererar är alltså inte alls i synk med hur det sedan stylas på riktigt och så länge vi har det byggt som det är idag så kommer den typen av problem att uppstå. 

**Utdrag från relevant kodsnutt genererad av TinyMCE för denna sida**
```
<h2 style="text-align: left;">Terapinytt</h2>
<p style="text-align: left;"><img class="wp-image-811 size-medium alignleft" src="http://vardgivare.regionhalland.se/app/uploads/2018/05/Terapinytt-nr-1-2018-204x300.jpg" alt="" width="204" height="300" /></p>
<p style="text-align: left;"><a href="http://vardgivare.regionhalland.se/app/uploads/2018/05/Terapinytt-nr-1-2018-webb.pdf">Terapinytt nr 1 2018</a></p>
<p style="text-align: left;"><a href="http://vardgivare.regionhalland.se/app/uploads/2018/05/877_RK_Broschyr_Terapinytt-nr-3-2017_v4.pdf">Terapinytt nr 3 2017</a></p>
<p style="text-align: left;"><a href="http://vardgivare.regionhalland.se/app/uploads/2018/05/Terapinytt-2-ny.pdf">Terapinytt nr 2 2017</a></p>
<p style="text-align: left;"><a href="http://vardgivare.regionhalland.se/app/uploads/2018/05/721_RK_Broschyr_Terapinytt-nr-1-2017_LO.pdf">Terapinytt nr 1 2017</a></p>
<a href="http://vardgivare.regionhalland.se/app/uploads/2018/07/Terapinytt-nr-4-2016.pdf">Terapinytt nr 4 2016</a>

<a href="http://vardgivare.regionhalland.se/app/uploads/2018/07/Terapinytt-nr-3-2016.pdf">Terapinytt nr 3 2016</a>
<h2></h2>
<h2></h2>
<h2></h2>
<h2>Läkemedelsenhetens nyhetsbrev</h2>
```
Koden tvättas inte vilket jag först trodde var problemet så kanske har Wordpress egna css-regler som vi skriver över. Det går att sätta "float:left" på img och clear:both på h2 och få det att fungera, men då gäller det alla och är frikopplat från knapparna i editorn. 

Jag är frestad att helt sonika stänga ned så mycket som möjligt av knapparna i TinyMCE så att beteendet styrs helt av .article. Då är det lättare att få ett konsekvent utseende. Men vill diskutera med @RolandHyden och @davidohlin

**Comment by regionhallandviktor** [comment]
Lät som du hade lite koll på vad som hände och hur man kan lösa det @davidohlin  Ta den gärna vidare. (Tar bort mig och @RolandHyden igen tills vidare)
