### ISSUE TITLE
Som besökare vill jag veta vilken flik jag har öppnat

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#107]
# User story
Som besökare vill jag veta vilken flik jag har öppnat

Problem: Utan markering är det inte bara otydligt vilken flik man kikar på. Det går också att tolka som att de tre spalterna är olika underrubriker till valen på nivå 1. 

# Acceptanskriterier

- [ ] Den flik jag öppnat på nivå ett markeras grafiskt. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information - skärmdump nuläge

![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/cdf97391-2075-4c02-8827-a4cf523d0264)

(Beklagar om det är en dubblett som jag inte minns)

**Comment by regionhallandviktor** [comment]
(Som synes ser det lite ut som att det finns massa underavdelningar till "Behandlingsstöd", "Medicinska områden" och "Service och IT" - trots att alla egentligen hör till Behandlingsstöd.

**Comment by JohannaOlin** [comment]
Denna är väl lite samma som https://app.zenhub.com/workspace/o/regionhalland/halland/issues/82?

**Comment by regionhallandviktor** [comment]
Liknande men inte samma :) #82 berör problemet som uppstår specifikt när man navigerat till en undersida längre i hierarkin. Den här uppstår på förstasidan.

**Comment by JohannaOlin** [comment]
Jag tycker nog att första acceptanskriteriet täcker in även detta
