### ISSUE TITLE
Menybugg - rubriknivå 1 stannar öppen när man klickar ner menyn

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#109]
Menybugg - rubriknivå 1 stannar öppen när man klickar ner menyn

Beskrivning: När jag är i mobilvyn och klickar ned menyn hålls nivå1-rubrikerna öppna. Gäller flera webbläsare och både mobil och dator. 

# Skärmdump

![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/8d2a69d6-a144-4c87-b00e-ad62acddfb08)

# Acceptanskriterier

- [ ] 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Fortfarande giltig.

**Comment by JohannaOlin** [comment]
Vi tar med denna i omarbetningen av menyerna.

**Comment by regionhallandviktor** [comment]
Släcker denna då den rör gamla designen.
