### ISSUE TITLE
Som besökare vill jag att Hitta på sidan följer med när jag scrollar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#110]
# Acceptanskriterier
- [x] Detta fungerar ok i Chrome, Firefox och Opera, men inte i övriga webbläsare

## Standard AC:s
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Nu ska den funka från IE10 och uppåt.

**Comment by regionhallandviktor** [comment]
Funkar i Chrome, Safari, Firefox och Opera på OSX samt vår IE och Edge på Win. @JohannaOlin @davidohlin
