### ISSUE TITLE
Som besökare vill jag se var i innehållsmenyn jag befinner mig

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#111]
# Acceptanskriterier

- [ ] Rubriker jag ser på sidan ska markeras grafiskt i innehållsmenyn (det kan vara flera samtidigt)
- [ ] När jag inte längre ser rubriken för stycket ska den inte vara markerad i innehållsmenyn

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by fridabergentoft** [comment]
Länk till skisserna för desktop, tablet och mobile: https://invis.io/56G43OEMST3
