### ISSUE TITLE
Som besökare vill jag förstå vilken webbplats jag är inne på

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#112]
# Acceptanskriterier

- [ ] se skiss https://invis.io/GHGBTKHTYEA

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Ligger på stage nu. Du ändrar texten via **Adminpanel > Utseende > Anpassa > Webbplatsens identitet > Slogan**
