### ISSUE TITLE
Som besökare vill jag att markering för aktivt val i huvudmenyn är så nära själva valet att kopplingen blir tydlig

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#130]
# User story
Som besökare vill jag att markering för aktivt val i huvudmenyn är så nära själva valet att kopplingen blir tydlig

# Acceptanskriterier

- [ ] Länkarna i huvudmenyn har en padding på ca 0.5rem istället för 1rem. 

# Skärmdump nuläge
![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/8de224bc-9613-4660-86f9-c856e76b20ed)

# Skärmdump förslag
![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/a4e90848-07bc-4c07-98a5-2e0e4d407a1b)

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Denna är inte aktuell längre
