### ISSUE TITLE
Nyheter på en Section Page

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#131]
# Beskrivning
Vi har behov av att kunna visa upp nyheter för olika områden, ex Läkemedel, vårdhygien. Detta urval av nyheter ska vi kunna visa upp på en section page.
- [ ] Som administratör kan jag lägga till nyhetskategorier
- [ ] Som redaktör kan jag tagga nyheten med en eller flera kategorier

# Skisser
I steg 1 visar vi upp nyheterna utan bild på section page
- [ ] Desktop : https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264071
- [ ] Tablet: https://projects.invisionapp.com/d/main#/console/12836247/317715859/preview
- [ ] Mobil: https://projects.invisionapp.com/share/FEFXVNIS39X#/screens/317715033

# Acceptanskriterier

- [x] Som redaktör kan jag välja en kategori av nyheter att visa på min section page
- [ ] Om redaktören inte väljer en kategori så visas alla nyheter på sidan
- [ ] Som redaktör kan jag ange en Rubrik för nyhetslistan på min section page
- [x] Som besökare ser jag nyhetens rubrik i listan
- [x] Som besökare ser jag datum för när nyheten uppdaterades
- [x] Som besökare ser jag den nyaste nyheten först/längst till vänster
- [ ] Som besökare ser jag början av brödtexten från nyheten. Detta avslutas med "..."
- [ ] Hela området för nyheten på section page är klickbar och leder till nyhetens fullpost
- [x] De tre senaste nyheterna visas på en section page
- [ ] Det finns en länk för att komma till ett nyhetsarkiv, en redaktör kan peka ut vilken sida länken ska leda till

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
- [ ] Nyheter är en komponent som kan läggas till på sidor
- [ ] RSS-flöde exponeras automatiskt.

**Comment by JohannaOlin** [comment]
Se skisserna för placering och utseende, https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264071.

**Comment by regionhallandviktor** [comment]
Jag assignar @RolandHyden för frontend och @davidohlin för backend. Visst håller du på med att konfa upp fält i backend som pekar ut vilka nyheter som skall visas på en sida David? Vi behehöver stämma av hur detta funkar så att vi hinner få igång funktionen den här veckan.

**Comment by regionhallandviktor** [comment]
Väntar här på David.

**Comment by regionhallandviktor** [comment]
David har byggt en lösning i backend och jag och Roland kikar på formateringen i frontend. Förhoppningsvis färdigt under dagen.

**Comment by regionhallandviktor** [comment]
Det blev färdigt idag. Två saker dock: @davidohlin  Jag har testat att lägga saker i excerpt-fältet i backend men det dyker inte upp i objektet. Har du någon koll på varför? Jag rotar i databasen imorgon tänker jag, men gött om du redan vet. 

Alla sidor kommer ha nyheterna som är generella om man inte aktivt väljer något annat. Det kanske är som avsett, men vill bara flagga upp eftersom jag var förvånad att samma nyhet syntes överallt på alla sub-startsidor.

**Comment by regionhallandviktor** [comment]
@davidohlin @RolandHyden  Jag har lagt in ett excerpt manuellt i WP admin som inte visas i frontend. När jag kör en var dump på nyhets-arrayen så är excerpt tomt. Visar sig att i tabellen wp_posts i databasen så är den faktiskt tom. Däremot så finns datat sparat i excerpt-fältet i tabellen wp_postmeta. Alltså kommer det inte över i rätt tabell som det var tänkt. Beror det på att det är ett ACF-fält som inte kopieras över till rätt tabell i databasen eller är det ett problem med vanilla WP? Får vi bara populerat fältet i rätt tabell så kommer det visas automatiskt.

**Comment by regionhallandviktor** [comment]
Vi behöver cappa antalet nyheter på section page till max 3 @RolandHyden

**Comment by regionhallandviktor** [comment]
Roland meddelat att han forskar i att begränsa antalet nyheter.

**Comment by regionhallandviktor** [comment]
Som det är byggt nu så verkar alla sidor defaulta till kategorin "Generell" vilket är en egen kategori.

**Comment by regionhallandviktor** [comment]
@davidohlin Stämmer det som jag fått intrycket av att sidor defaultar till kategorin "Generell"? Slår mig att acceptanskriteriet är att visa alla nyheter (dvs alla kategorier). 

Såg också att det finns ett kriterie för att ange en rubrik för nyhetslistan. Kan du lägga till ett sådant fält i widgeten för områdesnyheter? (Idag kör vi med "nyheter + sidtitel" vilket är quick fix, men blir konstigt när det faktiskt inte är nyheter specifikt för sidan de visas på. )

**Comment by regionhallandviktor** [comment]
Upptäckte att det finns två boxar för excerpt. En under innehållsbeskrivning som en tab och en som en egen ruta. Det är den understa som verkar vara Wordpress egen och fyller man i där funkar det redan.

**Comment by regionhallandviktor** [comment]
@RolandHyden Har berättat hur man cappar till tre nyheter. Jag har testat och det fungerar bra. Kommer en patch.
