### ISSUE TITLE
Som produktägare vill jag dölja taggmöjligheten på nyheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#133]
# Acceptanskriterier

- [x] Som redaktör kan jag inte märka min nyhet med en tagg

Taggarna behöver användas i bloggarna senare, men det blir antagligen för svårt för nyhetsredaktörerna att skilja på kategori och tagg.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Under *Utseende > Temainställningar > Nyheter* kan du välja att aktivera taggar nu. Tänker att vi samlar fler temainställningar där framöver.
