### ISSUE TITLE
Som besökare vill jag att det är tydligt hur länkar på översiktssidan väljs ut

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#166]
# User story
Som besökare vill jag att det är tydligt hur länkar på översiktssidan väljs ut

# Beskrivning 
"Topplänkar för dig" = personliga favoriter typ mina oftast besökta?
"Här hittar du de mest besökta länkarna" = Oftast besökta av folk i allmänhet

Påståendena krockar en aninge och i verkligheten har jag för mig att det är handplockade länkar vilket går på tvärs med båda.

# skärmdump
![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/b3ab32ea-75c4-4e94-a3fe-bc8f2196bf09)

# Acceptanskriterier

- [ ] Ledtexten speglar verkligheten. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Denna är inte aktuell längre
