### ISSUE TITLE
Som besökare vill jag kunna bädda in en film på sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#174]
# Acceptanskriterier

När jag klistrar in länken, ex <iframe class="streamio-player" width="560" height="315" src="http://streamio.com/api/v1/videos/5b05da5a6f8d8da738000002/public_show?player_id=4c9b6854b35ea807b5000001" frameborder="0" allowfullscreen></iframe> i textläget så ser allt bra ut tills dess att jag publicerar sidan, då försvinner texten och filmen visas inte.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Du kan använda en såkallad shortcode för det. Om du skriver `[video src="url_till_video.filformat"]` så borde den dyka upp. I detta fallet hade det alltså blivit `[video src="http://streamio-production.r.worldssl.net/videos/4ee87d8311581e02a60002a5_5b05da5a6f8d8da738000002_streamio-hq-480p.mp4"]`

Detta görs i tabben "Visuellt".

**Comment by davidohlin** [comment]
Framåt tänker jag att man skulle kunna ordna en knapp för att infoga video om det är ett vanligt case

**Comment by JohannaOlin** [comment]
Funkar perfekt. Jag kan lägga en story på knappen i iceboxen.
