### ISSUE TITLE
 RSS-flöde - Som besökare vill jag ha ett tydligare RSS-flöde

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#18]
## Acceptanskriterier
- [ ] Som besökare vill jag inte att datumet är länkat
- [ ] Som besökare vill jag ha en tydligare uppdelning mellan datum och rubrik på varje post

Den är till exempel inlagd på sidan http://stage-vardgivare.regionhalland.se/behandlingsstod/lakemedel/forskriva-och-ordinera-lakemedel/

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Kanske slår in öppna dörrar här, men för förstasidan borde det väl räcka att peka på "vardgivare.regionhalland.se/feeds" som ger förväntat RSS-flöde. Kruxet är kanske mest att vi behöver automatskapa länkar till rätt RSS-flöde när vi exponerar nyheter på olika platser i flödet, men den logiken finns redan gjord när vi pekar ut vad som skall visas i den lokala nyhetslistan. 

Om vi t.ex. vill ha okategorisersade inlägg så blir länken http://vardgivare.regionhalland.se/feed/?cat=okategoriserat.  osv. Det här är väl det vi kommer utnyttja för att separera vilka poster som visas vart och jag ser inget behov av egen logik för RSS eftersom WP redan exponerar RSS och kan göra det i flera olika format.

**Comment by regionhallandviktor** [comment]
Vill inte föregå @fridabergentoft vad gäller design, men när jag tänker på "förstå att det är separata poster" och "lätt att scanna" så föredrar jag något enligt följande

# förslag A
![image](https://user-images.githubusercontent.com/3371823/40424229-41d533aa-5e95-11e8-9f5f-184ff9bbaa94.png)

# Förslag B 
![image](https://user-images.githubusercontent.com/3371823/40424530-2a977878-5e96-11e8-844e-71438d497784.png)

@JohannaOlin

**Comment by regionhallandviktor** [comment]
Rotat lite i det och stämt av med David. Storyn har ett beroende till Modularity och kan lösas på tre sätt.
* Leta i modularity-dokumentationen hur man skriver över med en egen vy/blade-fil
* Göra en egen RSS-modul (blir då en egen plugin)
* Göra en pull request direkt till Modularity

**Comment by regionhallandviktor** [comment]
Note to self. Det är som väntat enkelt att nå första förslaget. Men lite pyssligare hur det skall förpackas eftersom det hänger på Modularity. Avvaktar Fridas input och gör det rätt från början. Men här är kod till blade-filen som gör fixar alt. 1. 

```
<div class="{{ $classes }}">
    @if (!$hideTitle && !empty($post_title))
    <h4 class="box-title">{!! apply_filters('the_title', $post_title) !!}</h4>
    @endif

	<ul>
	@if(! isset($items['error']))
		@foreach($items as $item)
			<li>
				@if(\Modularity\Module\Rss\Rss::getRssLink($item->get_link()))
					@if($date && $item->get_date('U'))
						<time class="date text-sm text-dark-gray">{{ date_i18n(get_option('date_format'), $item->get_date('U')) }}</time>
					@endif
					<a href="{{ \Modularity\Module\Rss\Rss::getRssLink($item->get_link()) }}">
						<span class="link-item title">{{ \Modularity\Module\Rss\Rss::getRssTitle($item->get_title()) }}</span>
					</a>
				@else
					<span class="title">{{ \Modularity\Module\Rss\Rss::getRssTitle($item->get_title()) }}</span>
					@if($date && $item->get_date('U'))
						<time class="date text-sm text-dark-gray">{{ date_i18n(get_option('date_format'), $item->get_date('U')) }}</time>
					@endif
				@endif

				@if($summary && \Modularity\Module\Rss\Rss::getRssSummary($item->get_description()))
					<p>{{ \Modularity\Module\Rss\Rss::getRssSummary($item->get_description()) }}</p>
				@endif

				@if($author && \Modularity\Module\Rss\Rss::getRssAuthor($item->get_author()))
					<p>{{ \Modularity\Module\Rss\Rss::getRssAuthor($item->get_author()) }}</p>
				@endif
            </li>
		@endforeach
	@else
		<li class="notice warning">
			<i class="pricon pricon-notice-warning"></i> {{ $items['error'] }}
		</li>
	@endif
	</ul>
</div>
```

**Comment by regionhallandviktor** [comment]
(att fetstila första ordet ger en ganska markant höjning av möjligheten att snabbt skumma, men kräver att man explode:ar strängen till en array och wrappar i en strong-tag och sedan gör en implode så gör inte det innan Frida sagt sitt.)

**Comment by regionhallandviktor** [comment]
@fridabergentoft   Får jag be om ett förhandsbesked - tror du att något åt det håll som skissats här kunde vara lämpligt istället för nuläget? Känner du att det behöver skissas på avvaktar jag, men annars är jag lite nyfiken på om jag kan paketera blade-filen jag tweakat så att vi kan använda den :)

**Comment by fridabergentoft** [comment]
https://invis.io/AEFT2NORHXU

**Comment by regionhallandviktor** [comment]
Tar tillbaka min önskan om att fetstila första ordet. Det har visat sig att första ordet inte nödvändigtvis alltid är ett medicinnamn och då faller också möjligheten att fokusera på det mest betydelsebärande ordet men en enkel regel.

**Comment by regionhallandviktor** [comment]
Den här är stängd, men pull requesten i #226 från augusti som skulle göra jobbet är öppen fortfarande. Kan du ta en kik @davidohlin och se om den borde mergas?
