### ISSUE TITLE
Som besökare vill jag att det är tydligt när menyn är stängd / öppen genom att hamburgerikonen blir ett X när menyn öppnas

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#182]
# User story
Som besökare vill jag att det är tydligt när menyn är stängd / öppen genom att hamburgerikonen blir ett X när menyn öppnas

# Beskrivning
Att hamburgermenyn förvandlas till ett "stäng"-kryss när man öppnar menyn är så vanligt att det nästan är en konvention. Om man animerar förvandlingen från tre sträck till ett kryss understryker man att något särskilt händer när man öppnar menyn. 

# Exempel
Jag gjorde en jsfiddle baserat på lite kod som jag lånade och anpassade https://jsfiddle.net/pfxrbv1q/  

# Acceptanskriterier

- [ ] När man öppnar menyn via hamburgerikonen så animeras den till ett kryss istället. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Lagd på omarbetningen issue 209 istället

**Comment by regionhallandviktor** [comment]
Fixad i en annan story (255 eller 254)
