### ISSUE TITLE
Som besökare vill jag lättare se vilka länkgrupper som hör ihop

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#189]
# Acceptanskriterier

- [ ] Det ska vara ett radbryt mellan sista länken i en länkgrupp och rubriken för nästa länkgrupp

![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/50dd881a-aad0-4b9f-948a-49b2410966af)

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
(Ser ut att vara fixad i prod - flyttar till closed)
