### ISSUE TITLE
Nyhet - Som besökare vill jag kunna läsa en nyhet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#19]
@JohannaOlin commented on [Mon Mar 05 2018](https://github.com/RegionHalland/vardgivarwebben/issues/37)

## Acceptanskriterier
- [ ] Som besökare ser jag vilka eventuella kategorier nyheten är taggad med
- [ ] Som besökare ser jag eventuella länkar som ligger som bilagor till nyheten
- [ ] Som besökare ser jag vem som är kontaktperson för nyheten
- [ ] Som besökare ser jag datum och tid för när nyheten senast uppdaterades
- [ ] Som besökare vill jag kunna navigera mig inom artikeln.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Går det att dölja kommentarsfunktionen? Jag vet att den frågan kommer att komma...

Vi behöver även visa upp de eventuella ämnen som en nyhet är taggad med

**Comment by simpel** [comment]
Exempel finns här: http://vg.digitaliseringsbyran.se/blog/2018/03/13/hello-world 

Ska fixa taggar och kategorier.

**Comment by regionhallandviktor** [comment]
Kikat på tillgängligheten, bra början! Kommentarer och annat kollar jag när det är skruvat på lite mer, men noterade två saker: 

- [ ] Kontrasten behöver upp för "publiceringsdatum" och "innehållsansvarig"

- [ ] Länken till innehållsansvarig blir helt utan kontext när man lyssnar på sidan. Ett vettigt title-attribut "Visa andra inlägg av den innehållsansvariga" eller att man kopplar ihop ledtexten med aria-labelledby vore bra. 

- [ ] Länk skall vara blå och understruken. (Behöver vi kanske snarare uppdatera globalt)

- [ ] Att innehållsansvarig-länken inte är en mailto är lite otydligt. Risken är att den förblir oklickad eftersom de som varit med lite längre avstår att klicka på något som ser ut som en mailto pga tidigare strul med att det öppnar mailprogram. 

**Förslag för diskussion**

**Innehållsansvarig:** Namn. 
[Alla inlägg av Namn](http://alla_personens_inlägg)

**Comment by JohannaOlin** [comment]
@simpel Hur gör jag för att dölja kommentarsfunktionen?
