### ISSUE TITLE
Som produktägare vill jag ha automatisk databas backup

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#195]
# Acceptanskriterier

- [ ] Det bör göras en gång per dag

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by RolandHyden** [comment]
Hej Johanna.
Jag har pratat med Thomas Persson som ska installera den nya servern. När servern är på plats så kommer också daglig backup att fungera. Såväl på filer som på databasen. Men vi får alltså vänta tills den nya servern är på plats.
