### ISSUE TITLE
Som besökare vill jag att rubriken ligger närmare texten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#196]
# Acceptanskriterier

- [ ] Minska mellanrummet mellan H2 och text och H3 och text

Titta t ex på sidan http://vardgivare.regionhalland.se/behandlingsstod/lakemedel/lakemedelsgenomgangar/

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by fridabergentoft** [comment]
https://invis.io/AEFT2NORHXU

**Comment by regionhallandviktor** [comment]
Finns en merge request på denna story nu. Men eftersom den ligger i ett annat repo kan jag inte koppla den till denna story.
