### ISSUE TITLE
Nyhetslista - Som besökare vill jag ta del av nyheter i sitt sammanhang

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#20]
@JohannaOlin commented on [Mon Mar 05 2018](https://github.com/RegionHalland/vardgivarwebben/issues/36)

## Acceptanskriterier
- [x] Som redaktör väljer jag vilken kategori av nyheter som ska visas på sidan
- [x] Som besökare ser jag i listan när nyheterna publicerades
- [x] Som besökare ser jag nyheternas rubriker i listan
- [x] Som besökare ser jag nyheterna listade efter senast uppdaterad överst
- [x] Som besökare vill jag kunna klicka mig vidare och läsa nyheterna
- [ ] Som redaktör kan jag ange hur många dagar bakåt i tiden som nyheter ska hämtas från
- [ ] Som redaktör vill jag kunna ange hur många nyheter som ska visas på sidan

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

**Comment by fridabergentoft** [comment]
https://invis.io/GHGBTKHTYEA skiss på en lång och kort nyhetslista

**Comment by regionhallandviktor** [comment]
Har kommenterat i invision (samt lite kommentarer på ngra andra sidor med)

**Comment by simpel** [comment]
Nu kan man se nyheter på http://stage-vardgivare.regionhalland.se/
