### ISSUE TITLE
Som besökare vill jag se en tydligare logga för webbplatsen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#205]
# Acceptanskriterier

- [ ] Se skiss https://invis.io/GHGBTKHTYEA
- [ ] Ändra storleken både på själva loggan och på texten "Vårdgivare Halland"

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
* Logga - be om en ny SVG fr Frida. (Går att skala upp SVG men såg lustigt nog lite knepigt ut)
* Storlek text - klassen site-nav__description i filen _site-nav.scss i styleguide.

**Comment by regionhallandviktor** [comment]
@JohannaOlin Finns större logga o rubrik enligt skissen, men David väntar med att pusha pga osäkerhet kring vilken design vi skall ha och hur det blev i mobilen.
