### ISSUE TITLE
Som redaktör vill jag kunna lägga in topplänkar på webbplatsen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#207]
# Acceptanskriterier

- [ ] Som redaktör kan jag ange ett länknamn
- [ ] Som redaktör kan jag lägga in en länkadress

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Presentationsmässigt är det rimligen _site-nav.scss i styleguide och nav-site.blade.php som berörs. Men hur länkarna skall registreras i WP är bra att stämma av med David - blir det t.ex. ACF-fält eller ngn annan customlösning.

**Comment by regionhallandviktor** [comment]
(Skall inte redaktörerna ändra sidhuvudets topplänkar på egen hand så föreslår jag att de läggs direkt i template-filen; det vore lättare att administrera om det är vårt team som har hand om ändringar)

**Comment by JohannaOlin** [comment]
Nej, redaktörerna behöver inte kunna ändra topplänkarna.

**Comment by JohannaOlin** [comment]
Jag har ändrat denna story så att det är en administratör som ska kunna lägga in dem. Visningen av topplänkarna ligger i en annan user story nu.

**Comment by regionhallandviktor** [comment]
Om jag minns rätt så blir det hårdkodade topplänkar och då blir storyn klar när den nya designen är implementerad. Sedan kan man med även minimala HTML-kunskaper ändra dem direkt på Github om man vill.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Denna story gäller endast redigeringen av topplänkarna, inte visningen av dem. Då är storyn färdig med andra ord? Jag förstår att vi behöver speca ner vilka som ska visas och vart de ska gå för att kunna lägga in något, men så länge det går att lägga in (även om de inte visas) så är ju storyn färdig. Visningen ligger i en story som handlar om att få in det nya sidhuvudet.

**Comment by regionhallandviktor** [comment]
Vi får kanske vänta med att släcka tills det faktiskt finns en fil att redigera, men ja - i princip är den här redan färdig i och med att man kommer kunna redigera filen och ingen ytterligare funktionalitet kommer att utvecklas.

**Comment by JohannaOlin** [comment]
Vi kör på en hårdkodad lista nu. Har vi senare behov av att redaktörerna själva kan ändra så skapar vi en ny story för det.

**Comment by regionhallandviktor** [comment]
Toppmenyn är inflyttad till blade-fil.   Det som är kvar är om Fridas ikon skall med in i styleguiden. Isf behövs en uppdatering av styleguiden.

**Comment by regionhallandviktor** [comment]
Denna finns på stage enligt nuvarande avgränsning om att hårdkoda. Låter storyn ligga kvar så får Johanna avgöra om vi skall göra en ny när vi bygger fält för länkarna.
