### ISSUE TITLE
Som produktägare vill jag se en förbättrad navigation

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#208]
# Beskrivning
Vi har ett behov av att kunna visa många ingångar på nivå 1. Detta går inte med en huvudmeny som visas i sidhuvudet. Enligt skisserna flyttas därför navigationen ner till scenen på startsidan, section overview och section page.

# Mål
När denna PBI är klar så ska det nya utseendet för navigationen vara på plats

# Skisser
- [ ] https://invis.io/TXNDSCO8YMA.
- [ ] Vänstermeny: https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/315784160

# Acceptanskriterier
- [x] Sidans barn visas mitt på sidan på sidtyperna startsida, section overview och section page enligt skiss 
- [x] I Steg 1 visar vi alla barn i navigationen. Vi behöver därför INTE lägga in en länk "Visa fler områden"
- [x] På sidtyperna Section overview och Section Page visas en blå platta under navigationen
- [x] I steg 1 visar vi endast sidans rubrik och pilen i navigationen, dvs inte texten under
- [ ] Hela plattan är länkad vidare till respektive sida
- [ ] På vanliga sidor visas barnen i en vänstermeny. Utseendet ska vara enligt skiss. 
- [x] Vänstermenyn ska fungera som idag

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Flyttar denna till in progress och assignar Roland.

**Comment by regionhallandviktor** [comment]
Roland och jag jobbar just nu med att populera med korrekt data.

**Comment by regionhallandviktor** [comment]
(Kommentaren ovan rörde "hamburgaren")

**Comment by regionhallandviktor** [comment]
Hamburgarmenyn hämtar korrekt data nu. Finns en commit som inkluderar detta på branchen newDesignLeverans

**Comment by regionhallandviktor** [comment]
Denna finns på stage men saknar ännu de delar som inte är ikryssade.

**Comment by JohannaOlin** [comment]
De två sista punkterna tar vi som nya issues. Jag tror dessutom att vi behöver diskutera logiken i vänstermenyn med intressenterna. Jag flyttar denna till Review.
