### ISSUE TITLE
Som besökare vill jag kunna öppna menyn från sidhuvudet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#209]
# Beskrivning
När vi flyttar huvudmenyn från sidhuvudet till scenen på startsidan så behöver vi lösa så att man kommer åt den från alla sidor även i desktop. Vi behöver även justera så att den fungerar på samma sätt i desktop, tablet och mobil. Vi börjar enkelt och förbättrar i senare sprintar.

# Skisser
- [ ] Desktop och tablet ser likadana ut, https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/313254414, men utan pilarna på nivå 2
- [ ] Mobil: https://invis.io/FEFXVNIS39X

# Acceptanskriterier

- [x] Hamburgermenyn visas även i desktopläget
- [x] Texten "Meny" ska visas bredvid "hamburgaren" i desktop och tablet.
- [x] Endast nivå 1 (Behandlingsstöd, Medicinska områden etc) öppnas när jag klickar fram Innehållsmenyn
- [x] När jag klickar på rubriken i menyn kommer jag till sidan.
- [ ] När jag klickar på pilen bredvid rubriken så öppnas nivå 2
- [ ] I första steget går det inte att öppna fler nivåer via hamburgermeny, det behövs därför inga pilar på nivå 2
- [ ] Gör om hamburgerikonen till ett "X" när menyn är öppen
- [ ] Om besökaren har fällt ut en nivå 1, dvs klickat på pilen bredvid rubriken så att nivå 2 öppnats och sedan fäller ut en annan nivå 1 så ska bägge nivå 1 vara utfällda
- [ ] Om besökaren har fällt ut en nivå 1 genom att klicka på pilen så kan hen fälla ihop den genom att klicka på pilen igen.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by fridabergentoft** [comment]
Mobile: https://invis.io/FEFXVNIS39X

**Comment by regionhallandviktor** [comment]
Assignar Roland för denna.

**Comment by regionhallandviktor** [comment]
Vi flyttade in i blade-filer i morse och det funkar som avsett. Första steget är att få in den i blade-filerna. Det här är den komponent som ligger längst ifrån färdigt så den skall få en del omsorg resten av veckan med. Förhoppningsvis hämtar den rätt data idag, men resten av veckan skall den nog stylas lite mer.

**Comment by regionhallandviktor** [comment]
Vi håller på att populera "hamburgaren" med korrekt data.

**Comment by regionhallandviktor** [comment]
Nu är hamburgaren populerad med korrekt data. Ligger en commit från Roland på newDesignLeverans-branchen.

**Comment by regionhallandviktor** [comment]
Standup idag. Roland har byggt så långt han kunde med befintlig kod. Men hamburgaren är en bit ifrån vad Frida skissat. Instruktion är att Roland lämnar vårdgivarwebben nu, men Digitaliseringsbyrån vill inte röra det Roland byggt. Jag kikar vad jag kan göra själv och försöker ta hjälp av Roland eller Digitaliseringsbyrån. Fokus måste vara att lösa demo på måndag.

**Comment by regionhallandviktor** [comment]
Hamburgermenyn är rätt långt ifrån skisserna och vi behöver se över den igen. Jag hittade lite buggar i funktionen som vi behöver fixa även om vi nöjer oss med befintligt utseende som en första version att iterera på. Men vågar inte vänta på att pusha till stage mer eftersom jag vill se om det är fler saker som dyker upp på stage.

**Comment by regionhallandviktor** [comment]
Checkat av boxarna. De som inte är ifyllda fungerar (om vi får ut den patchen jag lade till styleguiden) men inte riktigt enligt acceptanskriterierna.

**Comment by JohannaOlin** [comment]
Jag lägger upp nya issuses på det som återstår och sätter denna till Review.

**Comment by regionhallandviktor** [comment]
@JohannaOlin Hoppas det :) Kikar på det

**Comment by regionhallandviktor** [comment]
@davidohlin Jag tryckte ned ordet "Meny" för att centrera vertikalt lite bättre med "position: relative; top: 2px". Om du misstycker får du gärna göra något annat. Ligger i master, men inte på stage. Flyttar tillbaka issuen till QA och uppdaterar stage om ingen hojtar "neej" inom någon dag :)

(är inte så nöjd med själva lösningen - det borde styras med något som .align-middle men kruxet är att den inte ser rätt ut när den den rent "block"-mässigt är centrerad eftersom svansen på "y" sticker ned. Därför behöver den tryckas ned. Å andra sidan borde det bli fel om användarna sätter andra fontstorlekar. Provade att sätta största storleken i Chrome och upptäckte att fontstorleken är låst på väldigt många texter - det är kanske en story i sig)
