### ISSUE TITLE
Som besökare vill jag enkelt kunna nå föregående sida i sidhierarkin

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#210]
# Acceptanskriterier

- [ ] Gör det tydligt att det är bakåt/uppåt i sidhierarkin man går
- [ ] Gör det tydligt vilken sida man kommer till när man klickar 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Kan vi släcka den här? Tror den hör till gamla.
