### ISSUE TITLE
Som besökare vill jag hitta äldre nyheter

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#233]
# Beskrivning
De senaste nyheterna visas på startsidan för webbplatsen respektive på en section page. Vi behöver lista äldre nyheter i en arkivlista. 

# Acceptanskriterier
- [x] Lägg in länken Gå till nyhetsarkiv vid nyhetslistan på startsidan samt Section Page, för skiss se https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264073
- [x] Sidan har en rubrik
- [x] Sidan listar nyheter utifrån senast publicerad överst
- [x] Listan visar nyheternas rubrik samt nyhetens utdrag
- [x] Listan visar nyheternas publiceringsdatum
- [x] Nyheterna är klickbara och leder till respektive fullpost (nyhetsartikel)
- [x] Som redaktör kan jag peka ut vilka kategorier av nyheter som ska visas på respektive nyhetsarkiv, pekar jag inte ut något så visas alla

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by fridabergentoft** [comment]
Skiss finns under "Gå till nyhetsarkiv" 
https://invis.io/TXNDSCO8YMA

**Comment by JohannaOlin** [comment]
@fridabergentoft. Jag har skrivit lite kommentarer på skissen. @regionhallandviktor Kan du gå in och titta på skissen också?

**Comment by regionhallandviktor** [comment]
Finns arkiv-funktionalitet i kodbasen som vi förhoppningsvis kan tweaka.

**Comment by sebastiansson** [comment]
Jag har börjat jobbat med denna. 😀

**Comment by regionhallandviktor** [comment]
Såg att jag redan kommenterat den, men tog en runda till. Inga stora saker dock.
