### ISSUE TITLE
Sidhuvud

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#234]
# Beskrivning
I samband med att vi förändrar huvudmenyns placering behöver vi också förändra sidhuvudet. Utgå från Fridas skisser, se nedan, men i första steget behöver vi inte lägga in söket. 
- [ ] Hamburgermenyn som ska läggas in hanteras i PBI 209
- [ ] Skapandet av topplänkarna hanteras i PBI 207

# Skisser
- [ ] Desktop https://invis.io/TXNDSCO8YMA
- [ ] Tablet https://projects.invisionapp.com/d/main#/console/12836247/317715865/preview
- [ ] Mobil https://projects.invisionapp.com/share/FEFXVNIS39X#/screens

# Acceptanskriterier
- [ ] Lägg logga och texten "Vårdgivare Halland" i mitten
- [x] Loggan ska vara länkad till startsidan
- [x] Topplänkarna visas enligt skisserna
- [x] Topplänkarna presenteras från höger, dvs om det endast finns en så ska den ligga längst till höger.
- [x] Som besökare ska jag kunna nå menyn från sidhuvudet.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Lägger denna på Roland då det byggs utifrån dummy-siten.

**Comment by regionhallandviktor** [comment]
Sidhuvudet är inflyttat till blade-filer och vi håller nu på med hamburgermenyn som är sista delen
