### ISSUE TITLE
Nyheter på startsidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#235]
# Beskrivning
Förändring av utseendet på nyheterna som visas på startsidan. Eftersom vi i steg 1 inte kommer att ha blocket med Mina genvägar, Populära sidor och Senast besökta sidor så kommer Nyhetsblocket att hamna längre upp.

# Skisser
- [ ] Desktop: https://invis.io/TXNDSCO8YMA.
- [ ] Tablet: https://projects.invisionapp.com/d/main#/console/12836247/317715865/preview
- [ ] Mobil: https://projects.invisionapp.com/share/FEFXVNIS39X#/screens

# Acceptanskriterier
- [ ] De 5 senast publicerade nyheterna visas på startsidan, oavsett vilken kategori man har taggat nyheten med
- [ ] Senast publicerad visas överst
- [ ] Utseendet stämmer överens med skisserna
- [ ] Det finns en länk där besökarna kan prenumerera på RSS
- [ ] Rubriken för nyheten visas på startsidan
- [ ] Datum för publicering visas på startsidan
- [ ] 80 tecken av brödtexten för respektive nyhet visas på startsidan. Avsluta med "..." så att besökaren förstår att det finns mer text.
- [ ] Hela området för nyheten på startsidan är klickbar och leder till nyhetens fullpost
- [ ] Det finns en länk för att komma till ett nyhetsarkiv

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Sätter denna till in progress och Roland som assignee.

**Comment by regionhallandviktor** [comment]
@davidohlin Har för mig att du skulle bygga fält i backend för att peka ut vilka nyheter som skall visas på en sida - stämmer det? Jag tänker att vi börjar med att hårdkoda på samma sätt som det är gjort idag på startsidan, men att vi ändrar så fort som du är färdig med det arbetet.

**Comment by regionhallandviktor** [comment]
pratat med @RolandHyden och sagt att vi i första läget löser det likadant som idag - att det hårdkodas en hämtning av nyheterna. @davidohlin Tror du det är idé att lösa det på något annat sätt när vi nu kommer visa alla nyheter? (den här väljer ju inte ut bara en kategori så som nyheter på övriga gör)

**Comment by regionhallandviktor** [comment]
Roland och jag har lagt upp nyheterna på förstasidan så att de fungerar som idag. Det är en hårdkodad hämtning av det samlade nyhetsflödet på den WP-installation man är på.

**Comment by regionhallandviktor** [comment]
Note to self - de alternerande strecken behöver en nth-child i CSS för att bli varannan ljus/mörk. Det var hårdkodat i dummyn men skall ha lite logik i t.ex. main.scss om det inte kan hamna direkt i styleguiden.

**Comment by JohannaOlin** [comment]
Jag sätter över denna till Review nu så får vi ta resterande punkter i separata issues. Det kanske dessutom blir ändring när intressenterna tittar på det.
