### ISSUE TITLE
Sidfot

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#236]
# Beskrivning
Sajten behöver en sidfot där vi bland annat kan visa upp kontaktuppgifter. Denna PBI behandlar både visningen och redigeringen av innehållet i sidfoten.

# Skisser
- [ ] Desktop: https://invis.io/TXNDSCO8YMA.
- [ ] Tablet: https://projects.invisionapp.com/d/main#/console/12836247/317715865/preview
- [ ] Mobil: https://projects.invisionapp.com/share/FEFXVNIS39X#/screens

# Acceptanskriterier
- [x] Webbplatsens huvudmeny (nivå 1) ska visas under namnet på webbplatsen i första kolumnen (överst när man är i mobilläget). Huvudmenyn är länkad till respektive sida
- [x] Det går att lägga in ytterligare 3 kolumner med innehåll i sidfoten, dessa kan vara hårdkodade.
- [x] Det går att ange en rubrik för kolumnen
- [x] Det går att lägga text och länkar under rubriken

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
@davidohlin Gör du backend-logiken för detta? Vad sägs om att vi lägger in koden från dummy-siten i en blade-fil och vartefter du färdigställer fälten så kan du uppdatera blade-filen så den hämtar de fälten istället?     Så behöver bara jag och @RolandHyden vara synka vem som gör blade-filen för footern.

**Comment by regionhallandviktor** [comment]
Vi flyttade in sidfoten till blade-filer i förmiddags. Vi jobbar i en branch som heter newDesign på hallands-temat, men det mesta ligger nog lokalt hos Roland ännu. När backend-logiken är färdig så jackar vi in den så att redaktörerna enkelt kan ändra.

**Comment by regionhallandviktor** [comment]
Branch: newDesignLeverans. 

Sidfoten har ny blade-fil. Jag skall bara tighta till avståndet enl. Fridas synpunkter. Väntar på @davidohlin s backend-funktionalitet.

**Comment by regionhallandviktor** [comment]
Jag har lagt en commit på att minska avståndet mellan rubrik och text, men inte uppdaterat stage ännu eftersom det tog en god stund + raderar mitt git-repo och yarn. Tar allt i samlat trupp sedan.

**Comment by regionhallandviktor** [comment]
Centrerat texten på mobil med en tillfällig modul i main.scss. Syns när vi uppdaterar stage nästa gång.

**Comment by regionhallandviktor** [comment]
Justerat rubrikerna så att det stämmer bättre med skissen. Tänker att det är @fridabergentoft som behöva speca ytterligare ändringar (eller godkänna nuvarande utseende).
