### ISSUE TITLE
Brödsmuleväg

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#237]
# Beskrivning
I samband med att vi inför det nya utseendet behöver vi förändra utseendet även för Brödsmulevägen. Vi avvaktar med att lägga in brödsmulor i mobilläget.

# Skisser
- [x] Desktop: https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/315780183
- [x] Tablet: https://projects.invisionapp.com/d/main#/console/12836247/317715858/preview 

# Acceptanskriterier
- [x] Brödsmulevägen visas enligt skisserna, men låt alla länkar vara vita

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Detta ska vara fixat nu, se http://vardgivare.regionhalland.se/patientadministration/elektronisk-hantering-av-efrikort/.
Rensa cache om det inte dyker upp.

**Comment by JohannaOlin** [comment]
@davidohlin Kan du ta bort fetstilt på den sista nivån i brödsmulorna, dvs den sidan man är inne på. Det blev väldigt svårläst. Så får vi labba med detta sen när typsnittet är bestämt.

**Comment by davidohlin** [comment]
@JohannaOlin Fixat, hänger med i nästa release :-)

**Comment by davidohlin** [comment]
@JohannaOlin Det ligger uppe på stage nu.
