### ISSUE TITLE
Länkar som läggs in i modulen Linkgroup ska vara understrukna

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#238]
# Beskrivning
De länkar som läggs in i modulen Linkgroup är endast blå i dagsläget. Dessa ska ändras så att de även är understrukna.

Titta t ex på sidan http://stage-vardgivare.regionhalland.se/service-it/it-stod-och-system/medimaten/.
Länkar som är inlagda i editorn under rubriken "Rutiner" är korrekta, men den som är inlagd i modulen med rubriken Länkar är endast blå

# Mål
När denna PBI är klart så ska även en färgblind besökare förstå att länkar som läggs in i modulen Linkgroup är länkar.

# Acceptanskriterier

- [ ] Ändra så att länkarna i modulen Linkgroup är understrukna. Gäller desktop, tablet och mobil.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Detta ligger uppe på stage nu.
