### ISSUE TITLE
Synliggöra dummysiten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#239]
# Beskrivning
Vi behöver göra dummysiten synlig för intressenterna

# Acceptanskriterier

- [ ] Man kan klicka in på en github.io sida och få länkar till alla dummysitens sidor.
- [ ] Man kan titta på den i webbläsaren

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Tydlig prio 2/3 någonstans om den inte rentav redan har spelat ut sin roll. När vi väl lagt ut den nya designen är det inte säkert att vi behöver den alls. Stänger den tills vidare.

**Comment by regionhallandviktor** [comment]
Men om vi vill kunna göra den här typen av saker så behöver vi redan ut varför jag inte kunde skapa visningen av dummy-sajten direkt på regionhalland-kontot. Därav ping på Johanna - kan vara så att jag måste bli owner för att kunna lägga upp den.

**Comment by regionhallandviktor** [comment]
Tack @JohannaOlin  om du gjorde mig till owner. Nu ligger dummy-sajten på https://regionhalland.github.io/dummy_vg/ istället för min regionhallandviktor-adress och även om vi inte kommer använda den så mycket mer den här omgången så vet vi nu att det funkar till nästa gång.
