### ISSUE TITLE
Hitta på sidan - Som besökare vill jag se en innehållsförteckning på sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#24]
# Acceptanskriterier

- [ ] Som besökare vill jag se sidans underrubriker samlade i en innehållsförteckning
- [ ] Som besökare vill jag klicka på en länk i innehållsförteckningen och komma till rätt stycke på sidan
- [ ] Som besökare vill jag se i innehållsförteckningen var jag är på sidan
- [ ] Som besökare vill jag att innehållsförteckningen följer med när jag scrollar

Tillägg av Viktor 20 mars 2018
- [ ] Som besökare vill jag att rätt rubrik markeras i innehållsförteckningen även om den rubrik jag valt inte kan scrollas ända upp till toppen.
- [ ] Som besökare vill jag att den rubrik jag klickade på i innehållsförteckningen görs urskiljbar på själva sidan även om den inte kan scrolla till toppen. Exempelvis genom att en borttonande färgplatta visas bakom rubriken efter att sidan scrollat så långt som möjligt. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by simpel** [comment]
Exempel finns här: http://stage-vardgivare.regionhalland.se/nyheter/2018/04/30/en-nyhet-med-kommentarer-paslaget/

**Comment by JohannaOlin** [comment]
@simpel Kan du lägga in denna på vanliga sidor också?
