### ISSUE TITLE
Url-ompekning

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#243]
# Beskrivning
När vi byter vår externa webbplats (www.regionhalland.se) så behöver vi lösa ompekning av de vanligaste url:erna så att besökarna hittar rätt. Vi behöver ha en plan ganska snart så att vi kan involvera redaktörerna.

# Acceptanskriterier

- [ ] Kom fram med ett förslag på hur detta ska lösas.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Man kan sätta upp en custom url-struktur i WP så bara man vet vilka sidor som behöver heta likadant så är en kvalificerad gissning att det går att lösa bara genom att namnge likadant på den nya webben.   Ett par snabba jämförelser mellan regionhalland.se och nuvarande vårdgivarwebben visar också att vi redan strukturerar URL:erna på samma sätt. Så är man noga kommer bokmärken fortsätta fungera.

När det gäller kort-url:er från Episerver så motsvaras de av permalänk i WP och går att redigera på varje sida. 

Det som behövs är antagligen bara en lista på vilka URL:er i Epi som vi behöver vara noga med att sätta upp så de heter likadant i WP.

**Comment by JohannaOlin** [comment]
Issue moved to [RegionHalland/general #137](https://github.com/RegionHalland/general/issues/137) via [**ZenHub**](https://www.zenhub.com/)

**Comment by JohannaOlin** [comment]
Vi behöver titta på de mest besökta sidorna (topp 200?) och se till så att dessa url:er fungerar även när den nya regionhalland.se lanseras. Jag skapar ett separat kort för att plocka fram lista med snabblänkar
