### ISSUE TITLE
Topplänkar i mobilläget

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#244]
# Beskrivning
En besökare behöver kunna nå topplänkarna även i mobilläget.

# Acceptanskriterier

- [ ] Sajtens topplänkar ska visas även för de som besökare sajten i mobilläget

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
I nuläget ligger de kvar på samma sätt i mobil som i övriga layouter.
