### ISSUE TITLE
Aktivera Talande webb på vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#246]
# Beskrivning
Vi har köpt in verktyget Talande webb från Funka och vill lägga in detta i sidhuvudet på vårdgivarwebben. För att det ska gå att installera så måste url:en vara vitlistad. stage-vardgivare.regionhalland.se ska vara vitlistad, men det lär inte fungera på era lokala maskiner.

# Mål
När denna PBI är klar så kan besökarna aktivera Talande webb på vårdgivarwebben

# Acceptanskriterier

- [x] Installera Talande webb utifrån instruktionerna här www.funka.com/talandewebb
- [x] Lägg in länken "Talande webb" bland topplänkarna i sidhuvudet på Vårdgivarwebben
- [ ] När besökarna klickar på länken Talande webb så ska funktionen öppnas 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Lägger mig själv på denna tills vidare. Men kan behöva hjälp med hur skriptet skall köas i wp_footer.

**Comment by regionhallandviktor** [comment]
Jag har lagt in "Talande webb" nu enligt Funkas instruktioner. Ser rätt ut på min localhost även om den såklart inte är vitlistad, men scriptet laddar från browsealoud.com och länken syns som den skall. Men när jag uppdaterade stage så syns det inte. Gått igenom allt ett antal gånger, men nu bett David om hjälp.

**Comment by regionhallandviktor** [comment]
0.25 om det bara är stage som tappade uppdateringen och det i övrigt är klart.

**Comment by regionhallandviktor** [comment]
Pushade en annan patch till stage och då fixade sig den här med. Kollat igenom och det funkar som det skall. Sätter denna till QA.
