### ISSUE TITLE
Puffar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#248]
# Beskrivning
Som redaktör vill jag kunna lägga snabblänkar på startsidan på sajten. Denna PBI behandlar både det redaktionella och visningen av puffarna. I första steget gäller detta endast startsidan på sajten, men det kan bli aktuellt senare att lägga puffar på andra typer av sidor

# Skisser
- [ ] Desktop: https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264073
- [ ] Mobil: https://projects.invisionapp.com/share/FEFXVNIS39X#/screens
- [ ] Tablet: https://projects.invisionapp.com/d/main#/console/12836247/317715865/preview

# Acceptanskriterier

- [ ] Det ska gå att lägga in en bild för puffen
- [ ] Bilden ska automatiskt skala om till rätt storlek i desktop, mobil och tablet
- [ ] Det ska gå att lägga in text som visas på puffen
- [ ] Det ska gå att ange en länkadress för puffen
- [ ] Hela puffen (både bild och text) ska länkas 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
På god väg och snart färdig. Flyttar till in progress.
