### ISSUE TITLE
Separera nyhetsredaktörer från övriga redaktörer

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#252]
# Beskrivning
Vi behöver kunna lägga in redaktörer som endast får publicera inlägg, dvs inga sidor.

# Acceptanskriterier

- [ ] Vi kan lägga in personer som nyhetsredaktörer
- [ ] Nyhetsredaktörer kan skapa, publicera, ändra och ta bort nyheter
- [ ] Nyhetsredaktörer kan INTE skapa, publicera, ändra eller ta bort sidor
- [ ] De som är redaktörer för sidor ska också ha behörighet att publicera nyheter.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Jag tror att nyheter är löst med det som finns som default i gruppen "contributor" i vanliga Wordpress. Följande rättigheter har de:

**Contributor**
delete_posts
edit_posts
read

https://codex.wordpress.org/Roles_and_Capabilities

**Comment by regionhallandviktor** [comment]
Jag gör några tester för säkerhets skull så är det en sak mindre för dig David.

**Comment by regionhallandviktor** [comment]
Default för gruppen "medarbetare" är att de kan skriva inlägg och skicka till granskning (inklusive modularity-komponenter) men att de inte kan redigera dem sedan (eller redigera andras inlägg).

**Comment by regionhallandviktor** [comment]
Funkar bra både att ge "medarbetare" lite utökade befogenheter eller att skapa en helt ny grupp. På stage finns nu gruppen "Nyhetsredaktör" som har följande behörigheter: 

* create_posts
* delete_posts
* edit_others_posts
* edit_published_posts
* publish_posts
* read

Det finns en användare "nyhetsred" att testa med - sätt bara ett nytt lösen som admin vid användning eller skapa en egen användare. 

Hojta om samma inställningar skall replikeras på skarp server. Aktiverade tillfälligt "User role editor" som redan fanns installerat och den finns också på skarpa installationen så snabbt gjort att få det fixat. 

Ett aber bara - kolla att det som @sebastiansson gör med custom post type för nyheter inte stökar till det.

**Comment by regionhallandviktor** [comment]
För QA: Är beteende på stage det önskade (se ovan)? Isf kan jag eller någon annan lätt återskapa det på prod.

**Comment by JohannaOlin** [comment]
@regionhallandviktor När jag skapar en ny användare med behörigheten "Nyhetsredaktör" på stage så kan den endast redigera befintliga inlägg, inte skapa nya.

**Comment by regionhallandviktor** [comment]
@JohannaOlin Mycket knepigt eftersom jag gav dem både create och publish-behörighet samt verifierade att det funkade. Men jag har utökat så att nyhetsredaktörer har alla behörigheter som över huvud taget finns kring poster (=nyheter) och testkört med nyhetsred. Hoppas att jag bara missade något så det inte är något mer esoteriskt fel :)  Prova gärna igen - jag har testat med en användare med samma behörighetsgrupp som din.

**Comment by regionhallandviktor** [comment]
Den här får vi kika på igen :)

**Comment by JohannaOlin** [comment]
Issue moved to [RegionHalland/general #136](https://github.com/RegionHalland/general/issues/136) via [**ZenHub**](https://www.zenhub.com/)
