### ISSUE TITLE
Hamburgermenyn ska lägga sig ovanpå sidan under

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#255]
# Beskrivning
Idag hoppar sidans innehåll ner när man öppnar hamburgermenyn. Vi behöver ändra så att hamburgermenyn istället lägger sig ovanpå.

# Skisser
- [x] https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264073. Observera att utseendet på själva hamburgermenyn inte stämmer på skissen.

# Acceptanskriterier

- [x] Innehållet på sidan hoppar inte ner när användaren öppnar hamburgermenyn

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Jobbar med denna.

**Comment by regionhallandviktor** [comment]
Finns en branch på detta nu (255NewBurger). Utseende avstämt med Frida. Tänkte att jag skall ta overlay + knapp också innan den får komma in i master-branchen.

**Comment by regionhallandviktor** [comment]
Uppdaterat branchen med en overlay-funktion.

**Comment by regionhallandviktor** [comment]
Branchen har nu "stäng-krysset" också.

**Comment by regionhallandviktor** [comment]
Har utformat nya burgaren ihop med Frida. Nu flyter den som den skall. Synlig på stage.
