### ISSUE TITLE
Hela navigationsplattan ska vara länkad

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#256]
# Beskrivning
Idag är endast texten i navigationsplattan länkad, men vi vill att hela plattan ska vara länkad

# Acceptanskriterier
- [ ] Gör så att användaren kan klicka var som helst på plattan

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Börjar på denna. Försöker låna tänket från "hitta snabbt"

**Comment by regionhallandviktor** [comment]
Håller på och pushar till stage
