### ISSUE TITLE
Ändra innehållet i sidfoten på vårdgivarwebben

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#257]
# Beskrivning
Eftersom det inte framkom så mycket synpunkter på vad som ska visas i sidfoten på vårdgivarwebben så beslutar vi att ändra enligt nedan.

# Acceptanskriterier
- [x] Kolumn 2 Kontakt - Denna ska endast innehålla en länk "Kontakta Region Halland" - adressen ska vara https://www.regionhalland.se/kontakta-oss/.
- [x] Kolumn 3 Övriga webbplatser - Ska ha följande länkar www.regionhalland.se samt "Regionens intranät" länkat till https://intra.regionhalland.se/Sidor/default.aspx.
- [x] Kolumn 4 ska ändras till "Webbplatsen". Här ska visas en länk "Om webbplatsen" denna ska länkas till http://vardgivare.regionhalland.se/valkommen-till-vardgivarwebben/om-webbplatsen/ samt "Dataskydd" som ska länkas till https://www.regionhalland.se/om-region-halland/organisation/dataskydd/

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Fixat infon i footern. Pushat till master-branchen. Syns nästa gång vi uppdaterar stage.

**Comment by JohannaOlin** [comment]
@regionhallandviktor Frågan är om vi inte ska ändra adressen till regionhalland till https. Det funkar med http också, men det är väl bättre att använda https?

**Comment by regionhallandviktor** [comment]
@JohannaOlin Region Halland använder än så länge http. Om man anropar via https så pekas om tillbaka till http. Jag skulle tro det händer på serversidan så att det inte spelar någon roll vilken webbläsare man har, men det känns mer korrekt att använda det protokoll som faktiskt används (http) så byter vi till https i sidfotslänken när regionhalland.se aktiverar det.
