### ISSUE TITLE
Brödsmulevägen måste bli smalare

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#258]
# Beskrivning
Brödsmulevägen är alldeles för hög nu.

# Skisser
https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/315780183

# Acceptanskriterier
- [x] Brödsmulevägen ser ut som på skisserna, både på vanliga sidor och på section overview och section page.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Tightat till padding för brödsmulor + rubriken. Pushat till masterbranchen så syns när vi uppdaterar stage.
