### ISSUE TITLE
Rubriken på Section overview ska ligga i det blå fältet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#259]
# Beskrivning
Rubriken visas idag (på Stage) under navigeringen.

# Skiss
- [x] https://projects.invisionapp.com/share/TXNDSCO8YMA#/screens/314264072

# Acceptanskriterier
- [x] Flytta upp rubriken till det blå fältet enligt skiss

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [x] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Fixad. Pushad till master-branch. Syns nästa gång vi uppdaterar stage.
