### ISSUE TITLE
Ta bort senast ändrad från Section Page och Section overview

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#260]
# Beskrivning
På Section overview och Section Page visas idag senast ändrat datum, men dessa sidor kommer inte att uppdateras speciellt ofta.

# Acceptanskriterier
- [x] Visa inte upp datum och klockslag för senast uppdaterad på dessa sidtyper

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Plockat bort informationen från dessa sidmallar. Pushat till master-branchen. Syns nästa gång vi uppdaterar stage.
