### ISSUE TITLE
Ta bort extra rubrik på Section Page

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#261]
# Beskrivning
Nu visas sidans rubrik på två ställen på en Section Page, dels uppe i det blå fältet och dels nere under Nyhetslistan

# Acceptanskriterier
- [x] Ta bort den automatiska rubriken som visas under nyhetslistan
- [x] Redaktören kan själv lägga in en rubrik ovanför textfältet om det behöver finnas någon

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Pushad till master-branchen. Syns nästa gång vi uppdaterar stage.
