### ISSUE TITLE
Plocka bort nivå två från hamburgermenyn

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#264]
# Beskrivning
Vi fick synpunkter på sprintdemon att man tyckte att det var för många olika sorters navigation. För att få det lite tydligare visar vi endast nivå 1 i hamburgermenyn

# Acceptanskriterier
- [ ] Ta bort nivå 2 från hamburgermenyn
- [ ] Gör nivå 1 klickbar

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Fixat och pushat till master-branchen. Syns när vi uppdaterar stage.
