### ISSUE TITLE
Redaktörer vill kunna sortera om sidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#269]
# Beskrivning
Eftersom vi tänker oss att endast ha få redaktörer för sajterna så vill vi att dessa enkelt ska kunna flytta sidor i strukturen. När en med behörigheten Redaktör gick in och skulle dra och släppa en sida i strukturen för att ändra ordningen på undersidorna så gick inte detta. 

# Acceptanskriterier

- [ ] Som redaktör kan jag enkelt sortera om sidor i samma träd

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Till den som får storyn assignad: gå in på inställningar / "Nested pages" (den plugin som används) i stage och testa att slå på den här inställningen
![image](https://user-images.githubusercontent.com/3371823/48898676-a7ce2e80-ee4d-11e8-887c-23807b2912cf.png)

**Comment by JohannaOlin** [comment]
Issue moved to [RegionHalland/general #105](https://github.com/RegionHalland/general/issues/105) via [**ZenHub**](https://www.zenhub.com/)
