### ISSUE TITLE
Innehållsansvarig - Som redaktör vill jag kunna lägga in en innehållsansvarig på sidan

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#27]
# Acceptanskriterier

- [x] Som redaktör behöver jag inte lägga till komponenten på varje sida
- [x] Som redaktör vill jag lägga till en e-postadress för ansvarig (*)
- [x] Som redaktör kan jag skriva in ett namn på den som är ansvarig för sidan

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [x] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [x] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
Så småningom vill vi göra det möjligt att dölja innehållsansvarig på enstaka sidor. Vi vill också så småningom göra det möjligt för besökarna att kontakta innehållsansvarig via ett formulär, i första steget ska det alltså inte vara möjligt att kontakta innehållsansvarig.

**Comment by JohannaOlin** [comment]
Efter dialog med Johanna (Kommunikationsdirektören) så vill vi inte visa personens namn på sidorna. Denna story kan därför ändras så att den enbart gäller att redaktören ska kunna skriva in namn och e-post till den som är innehållsansvarig. Så småningom kommer vi på sidorna att visa "Kontakta innehållsansvarig" med en länk till ett kontaktformulär. Men det blir en ny story. 

Vi kommer heller inte att behöva dölja funktionen på sidorna.

**Comment by davidohlin** [comment]
Detta är på plats nu, det ligger en ruta under varje sida i admingränssnittet. In och kolla på [http://vg.digitaliseringsbyran.se](http://vg.digitaliseringsbyran.se)!
