### ISSUE TITLE
Länkar - Som besökare vill jag se länkar som är kopplade till sidan/nyheten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#28]
# Acceptanskriterier

- [x] Som besökare kan jag se länkgruppens rubrik
- [x] Som besökare kan jag klicka på länken för att komma vidare
- [x] Länkgruppens rubrik ska vara en H2 så att den kommer med i Hitta på sidan komponenten
- [x] Modulen ska byta namn till Länkgrupp
- [x] Tidigare instanser av modulen ska funka som tidigare

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
Detta ligger uppe på stage nu. Tidigare instanser av accordion borde heta linkgroup och funka som tidigare, samt att den dyker upp i innehållsnavigeringen nu, [exempel här](http://stage-vardgivare.regionhalland.se/behandlingsstod/lakemedel/bestalla-lakemedel/)

**Comment by JohannaOlin** [comment]
Länkarna visas två gånger på en nyhet http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/nyhetstest/

**Comment by davidohlin** [comment]
@JohannaOlin Ska vara fixat nu! [http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/nyhetstest/](http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/nyhetstest/)
