### ISSUE TITLE
Vårdgivarwebben ska vara sökbar via google

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#280]
# Beskrivning
Vårdgivarwebben (ej stage) verkar inte vara sökbar via google. Vi behöver lösa så att den blir det.

# Acceptanskriterier
- [ ] Det ska gå att söka på google och få träff på vårdgivarwebben

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Jag lyckas få träff på själva sajten (även när jag kör incognito utan cookies) utan större problem. Lyckas även få träff på undersidor som vid sökning på t.ex. "tandvård vårdgivare halland". Men det kan ändå vara värt att se över om t.ex. den här storyn om att serva en sitemap (XML-data - inte en grafisk för användare) https://github.com/RegionHalland/halland/issues/217  (om det nu inte redan görs utan att själva storyn är släckt)

Sedan finns det en hel del andra saker man också behöver kolla igenom för att förbättra rankningen
