### ISSUE TITLE
Produktionsmiljö - Som produktägare vill jag ha en produktionsmiljö för siten

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#29]
# Acceptanskriterier

- [x] Sätt upp en Azure-server
- [x] Ta fram en ny ssh-nyckel för produktionsservern
- [x] Flytta innehåll från staging till produktion
- [x] Ta fram dokumentation för hur produktionssättning bör gå till (Jonas?)
- [x] vardgivare.regionhalland.se ska pekas om till produktionsservern
- [x] Meddela Nils att siten ligger live
- [x] Innehållet från TR ska finnas tillgängligt på vårdgivarwebben

## Terapirekommendationer

- [x] Kolla att uploads funkar
- [x] Länkar i content funkar
- [x] Hur gör vi med länkstrukturen? -> Låt vara som den är
- [x] Diff ser annorlunda ut
- [x] Diff funkar inte som den ska, ändringar görs när vi skapar en revidering
- [x] Arbetsflöden från live ska in, men inte publiceras än.
- [x] Fixa mailserver, kolla sedan att mail funkar - Behöver sätta MX-records för att få Mailgun att funka.
- [x] Sökfunktionen funkar som det ska
- [x] Kolla arbetsflödet med Anton
- [x] Dubbelkolla att analytics funkar som tidigare
- [x] Dubbelkolla att hotjar funkar som tidigare
- [x] Kolla att [https://github.com/RegionHalland/vardgivare.regionhalland.se/issues/5](https://github.com/RegionHalland/vardgivare.regionhalland.se/issues/5) är löst

**Comment by simpel** [comment]
Servern och nyckel är skapad men är tom. Finns på 52.164.247.227.
