### ISSUE TITLE
Publiceringsdatum - Som besökare vill jag se när sidan uppdaterades så att jag ser om informationen är aktuell

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#30]
# Acceptanskriterier

- [x] Klockslaget på servern ska vara rätt
- [x] Se Stilguiden i wikin för kontrastvärde

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [x] Lösningen har kodgranskats av en kollega
- [x] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [x] Storyn har synkats med övriga produktägare
- [x] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
Så småningom ska det gå att dölja publiceringsdatum på enstaka sidor
Redan idag visas det ett senast uppdaterat datum på sidorna, men dels blir klockslaget fel och dels tycker jag att det räcker att vi visar datum. Vi behöver också fundera på formatet på datumet.

**Comment by davidohlin** [comment]
Har uppdaterat tiden på prod och stage!
