### ISSUE TITLE
Som produktägare vill jag se en skiss på webbplatsens startsida inkl sidhuvud och sidfot

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#33]
# Acceptanskriterier

- [x] Skissen ska innehålla en logga
- [x] Skissen ska innehålla sitenamn
- [x] Skissen ska innehålla möjlighet för besökarna att navigera till innehållet på sajten
- [x] Skissen ska innehålla sökruta
- [x] Skissen ska innehålla hur man navigerar till regionens övriga webbplatser
- [x] Skissen ska innehålla kontaktinformation till regionen
- [ ] Skissen ska innehålla inloggningsmöjlighet 
- [ ] Skissen ska innehålla information om vem som eventuellt är inloggad
- [x] Skissen ska innehålla snabblänkar (ex Anslagstavla, Akuta situationer)
- [x] Skissen ska innehålla länkar till Lyssna, byta språk, webbplatskarta alternativt A-Ö
- [x] Skissen ska innehålla länkar till våra konton i sociala medier
- [x] Skissen ska innehålla disposition av startsidan; puffar, nyhetslista mm

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
Se underlag från Martina nedan

**Comment by JohannaOlin** [comment]
## Underlag från Martina

Att ta fram ett UX-ramverk för regionens webbplatser
Syftet med att införa ett nytt arbetssätt kring våra webbplatser är att leverera verksamhetsnytta snabbare med bibehållen förvaltingsbarhet. För att lösa detta byggs ett komponentbibliotek av funktioner som ska kunna användas när våra webbplatser behöver utvecklas alternativt när nya behöver sättas upp. Teamet som bygger komponenterna arbetar i nära dialog med de personer som skapar det redaktionella innehållet samt intressenterna i verksamheten.
En del i den plattform som byggs upp är ett ramverk för UX och grafisk form, en konkretisering av regionens varumärke och grafiska profil. Ingångsvärden är att det som byggs ska vara tillgängligt för alla enligt WCAGs standard, fungera både på desktop och mobilt samt vara skalbart så att det kan byggas på efterhand.
Ramverket ska användas för samtliga webbplatser inom Region Halland. Det innebär att det ska fungera för huvudsajterna (i nuläget vårdgivarwebben, regionhalland.se och intranätet), kampanjsajter (till exempel Rum för dans  och Art inside out) och samarbetssajter som vi till exempel hanterar tillsammans med kommunerna.
Ramverket behöver definiera utseende och funktion för:
•	Navigering – huvudnavigering och sidonavigering
•	Länkstig
•	Möjlighet att välja profil på sidan alternativt logga in
•	Navigering mellan regionens olika webbplatser
•	Teckensnitt, bildspråk
•	Disposition av startsidor – text, bilder, ”puffar” etc
•	Sidfot
•	Profilering av en specifik vårdcentral eller skola inom den gemensamma designen
•	Presentation av e-tjänster.
•	?
Kopplingar till andra projekt och initiativ
•	Kommunikationsavdelningen arbetar med att uppdatera den grafiska profilen utifrån det nya varumärket. Det finns ett underlag som inom kort går ut för upphandling. Viktigt att UX-ramverket synkar med det arbete som görs inom den grafiska profilen. 
Kontaktperson: Sandra Sutt Stawreberg
•	Arbetet med vårdgivarwebben har påbörjat arbetet med att bygga komponenter. I deras arbete har det kommit fram en hel del behov, bland annat vad gäller navigering i flera nivåer och möjligheten att ”profilstyra” innehåll.
Kontaktperson: Johanna Olin 

Ett arbete har gjorts kopplat till Folktandvården på webben och i det arbetet finns en hel del erfarenheter och slutsatser kring behovet av att profilera en verksamhet inom den gemensamma profilen.
Kontaktperson: Joel Sandén

**Comment by JohannaOlin** [comment]
- Vi måste kunna ha många ingångar. I dagsläget har vi 6 ingångar för vårdgivarwebben, 6 för regionhalland.se samt 6 för intranätet
- Vi vill att sökrutan ska kunna vara synlig
- Vi kan inte skriva Vårdgivarwebben ihop med loggan utan det måste stå för sig själv

Titta även på embryot till stilguide som Viktor har tagit fram, ligger i Wikin i teamet.

**Comment by JohannaOlin** [comment]
@fridabergentoft Justera skissen enligt underlag från Maria så anser vi att denna är klar sedan.

**Comment by JohannaOlin** [comment]
@fridabergentoft Uppdatera den också enligt Viktors kommentarer. 

Jag kommer att skicka ut länken till skissen till de som var på Sprintdemon så det är möjligt att det kommer fler kommentarer, men dessa sparar vi i så fall tills vi diskuterat igenom dem.

**Comment by fridabergentoft** [comment]
Länk till skiss på startsida: https://invis.io/GHGBTKHTYEA

**Comment by regionhallandviktor** [comment]
@fridabergentoft Jag kommenterade de nya skisserna lite i invision.
