### ISSUE TITLE
Stilguide - Som team vill vi ha riktlinjer för det grundläggande uttrycket

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#34]
# Acceptanskriterier
- [ ] Typsnitt
- [ ] Textstorlekar (löptext, H1, H2, menyer etc)
- [ ] Länkar (utseende, funktion)
- [ ] Kontrastvärden

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Gjort en sida på Digitala kanaler/wiki med detta. Slutgiltigt besked om typsnitt har vi inte ännu, men vi kan börja med Scala och se vad vi tycker. Textstorlekar har jag skrivit det vi behöver veta ur strikt WCAG-perspektiv och i övrigt vill jag diskutera med t.ex. Frida imorgon.
