### ISSUE TITLE
Som redaktör vill jag kunna ladda upp filer som är större än 1 MB

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#40]
# Acceptanskriterier

- [x] Som redaktör vill jag kunna lägga upp filer som är upp till 32 MB

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by JohannaOlin** [comment]
Detta funkar bra i stage nu, kan vi fixa det i produktionsmiljön så snart som möjligt?

**Comment by davidohlin** [comment]
@JohannaOlin Trodde det funkade i produktion också, jag kikar på det!

**Comment by JohannaOlin** [comment]
@davidohlin Det står http fel när jag försöker ladda upp en tung fil. 

![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/a4f63fd2-73d4-43bc-a2a6-26c30bbcce02)

**Comment by davidohlin** [comment]
Hade missat att ändra i nginx-configen för produktionssiten, nu ska det vara fixat. 👍

**Comment by JohannaOlin** [comment]
Nu funkar det fint

**Comment by JohannaOlin** [comment]
Hm, nu såg jag att gränsen i produktion var satt till 2 MB, men i stage till 30 MB. Vi behöver ha lite mer än 2 i alla fall.

**Comment by davidohlin** [comment]
Okej, något är skumt med inställningarna då. Jag kikar igen.

**Comment by JohannaOlin** [comment]
Gissar att det beror på att utrymmet är nästan fullt 

![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/aaaf4f8d-ea1f-4972-9aa2-6d19e66d9bd8)
