### ISSUE TITLE
Som redaktör vill jag kunna presentera innehåll i någon form av lista 

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#56]
# Acceptanskriterier
Vi behöver kunna presentera information som den som finns i bilden nedan.
![image.png](https://images.zenhubusercontent.com/5a587a674b5806bc2bc279a7/7faf1385-1ec5-45bb-b1d8-3374ba09acd7)

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
Den befintliga listan hittar ni här https://extra.regionhalland.se/halsa-vard-tandvard/lakemedel/ordnat%20inforande/Sidor/Regionala-beslut.aspx

Jag tror inte att det finns så många tabeller/listor på extranätet idag, men även Analysförteckningen som ligger på regionhalland.se, http://www.regionhalland.se/vard-halsa/for-vardgivare/laboratorier/analysforteckning/?chars=A presenteras i en tabell.

**Comment by fridabergentoft** [comment]
Länk till skisser: https://invis.io/AVJL6A5E9B4

**Comment by regionhallandviktor** [comment]
Snyggt jobbat @fridabergentoft! Grundutseendet är bra och jag har kommenterat loss. Det är lite smått och gott men bara tweaks och inga saker som kräver att man börjar om.

**Comment by regionhallandviktor** [comment]
Gillar den uppdaterade verisionen. Tycker vi kör så.
