### ISSUE TITLE
som besökare vill jag kunna urskilja länkar

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#68]
# User story
som besökare vill jag kunna urskilja länka

# Acceptanskriterier

- [x] Alla textlänkar är understrukna och blå i enlighet med stilguiden i wikin. 

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [x] Lösningen har kodgranskats av en kollega
- [x] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [x] Storyn har synkats med övriga produktägare
- [x] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
Ligger uppe på stage nu. @JohannaOlin @regionhallandviktor

**Comment by regionhallandviktor** [comment]
Gött! Feedback: 
1) Färgen behöver dock justeras, är nu #0b457e; och vår stilguide anger: 

Vanlig länk: #0041b0;        (kontast 8.81:1 mot vit)
Besökt länk: #909;             (kontrast 7.46:1 mot vit)

2) Länkarna behöver vara understrukna på nyheter också som inte är en del av article-klassen.

**Comment by davidohlin** [comment]
1. Jag använde basblå som används över siten, den har högre kontrast mot vit så den borde funka. Vet inte exakt var #0041b0 kommer ifrån, men känns mer rimligt att behålla den än att ändra över hela siten/definiera en ny blå tänker jag!

2. Det ska dem vara, kan vara så att styleguiden är cachad kanske. Testa att gå [hit](http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/innehallsnyhet/) och göra en hård inläsning (⌘+Shift+R på OSX, Ctrl+Shift+R på Windows)! Annars får jag kika på det! 👍

**Comment by regionhallandviktor** [comment]
1) Jag missade att berätta att det inte bara är kontrast mot vitt som är intressant utan minst lika viktig är kontrast mot svart. För de som inte ser färg så är det kontrasten mellan färgerna som gör att man separerar ut dem. Nu kör vi ju med understruket så vi är inte beroende av det, men för länkar som t.ex. under "kategorier" och "länkar" på http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/nyhet-med-lankar/ så hade det varit en hjälp med större kontrast mot svart också - alternativt att vi stryker under dessa med. 

2) Den du länkar till ser helt ok ut men den här vill inte (varken med hård inläsning eller med devtools öppet som inaktiverar cace) http://stage-vardgivare.regionhalland.se/nyheter/2018/05/22/nyhet-med-lankar/

**Comment by regionhallandviktor** [comment]
Enklast är nog helt sonika att vi tar några minuter och kikar direkt på skärmen.

**Comment by regionhallandviktor** [comment]
Ping @davidohlin förresten om inte kommentarerna ovan syns - jag har precis själv ändrat så att mentions genererar epost till mig :)

**Comment by regionhallandviktor** [comment]
@davidohlin @JohannaOlin Länkar som ligger i "länkar"-boxen är fortfarande inte understrukna så jag avvaktar med att stänga den här tills vidare.

**Comment by JohannaOlin** [comment]
Jag har lagt en ny PBI på länkar i modulen Linkgroup istället så jag stänger denna.
