### ISSUE TITLE
Lyssna på en standardsida

### ISSUE THREAD

**Issue by simpel** [RegionHalland/halland#7]
# User story
Som besökare vill jag kunna lyssna på informationen på en standard sida

# Acceptanskriterier
- [ ] Implementera den lösning vi har idag på regionhalland.se
- [ ] Funktionen är i nära anslutning till sidans primära innehåll

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
Släcker denna då talande webb har en egen story.
