### ISSUE TITLE
Som redaktör vill jag kunna lägga in en innehållsansvarig på en nyhet

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#73]
# Acceptanskriterier

- [x] Som redaktör behöver jag inte lägga till komponenten på varje nyhet
- [x] Som redaktör kan jag skriva in en namn på den som är ansvarig för nyheten
- [x] Som redaktör kan jag skriva in en e-postadress till den som är ansvarig för nyheten
- [x] Som besökare ser jag inte vem som är ansvarig för nyheten

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [x] Lösningen har kodgranskats av en kollega
- [x] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [x] Storyn har synkats med övriga produktägare
- [x] Lösningen går i linje med WCAG 2.0 AA

# Övrig information
Vi vill så småningom göra det möjligt för besökarna att kontakta innehållsansvarig via ett formulär, i första steget ska det alltså inte vara möjligt att kontakta innehållsansvarig.
Vi vill även så småningom koppla detta mot AD:t så att redaktören kan välja en person istället för att manuellt skriva in uppgifterna.

**Comment by davidohlin** [comment]
Detta är fixat och ute på stage. Komponenten är tillbaka och finns under nyheter, samt att Innehållsansvarig inte printas ut på nyheter eller sidor. @JohannaOlin
