### ISSUE TITLE
Som besökare vill jag se vilken flik som är öppen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#82]
# Acceptanskriterier

- [x] Den flik som är öppen ska vara den som markeras grafiskt även om sidan under tillhör en annan flik, detta gäller även om den underliggande sidan är Startsidan
- [x] Om jag sedan klickar utanför menyn så att jag kommer tillbaka till min ursprungssida så ska den grafiska markeringen flyttas tillbaka till aktuell flik.

Dvs Om jag har sidan Läkemedel uppe så ska menyvalet Behandlingsstöd vara markerat. Om jag sedan klickar på Kompetens och utveckling i huvudmenyn så att denna fälls ner så ska valet Kompetens och utveckling vara markerat även fast den underliggande sidan är Läkemedel. Klickar jag utanför menyn för att komma tillbaka till sidan Läkemedel så ska Behandlingsstöd markeras igen.

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin @regionhallandviktor Detta ligger uppe på stage nu. Det innebar vissa ändringar i styleguiden, så börja med att göra en hård omladdning av sidan med Ctrl+Shift+R för att rensa cache.

**Comment by regionhallandviktor** [comment]
Gött - funkar precis som avsett och känns väldigt naturligt. Testat i Chrome, Safari, Opera, Firefox och Crome. @JohannaOlin @davidohlin  Jag har inga invändningar.

**Comment by regionhallandviktor** [comment]
(Samt Edge och Safari)

**Comment by regionhallandviktor** [comment]
@davidohlin förresten - såg lite ändrat beteende på prod, men det beror väl rimligen på att du ändrat i styleguide som används av båda, men WP-koden inte är pushad till prod ännu?
