### ISSUE TITLE
Som besökare vill jag att länkstigen märks ut som länkstig

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#83]
# Acceptanskriterier

- [x] Aria label = länkstig
- [ ] wrappa ol i ett nav-element istället för div. 
- [x] sidan man är på skall märkas upp med aria-current="page"

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
<ul aria-label="länkstig">

**Comment by regionhallandviktor** [comment]
Lade till två acceptanskriterier. Lånar en snutt exempelkod från W3C för tydlighetens skull. 
  ```
<nav aria-label="Breadcrumb" class="breadcrumb">
    <ol>
      <li>
        <a href="../../">
          WAI-ARIA Authoring Practices 1.1
        </a>
      </li>
      <li>
        <a href="../../#aria_ex">
          Design Patterns
        </a>
      </li>
      <li>
        <a href="../../#breadcrumb">
          Breadcrumb Pattern
        </a>
      </li>
      <li>
        <a href="./index.html" aria-current="page">
          Breadcrumb Example
        </a>
      </li>
    </ol>
  </nav>
```
