### ISSUE TITLE
Som redaktör vill jag enklare kunna sortera undersidor

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/halland#84]
# Acceptanskriterier

- [ ] Gör det möjligt att dra och släppa vid sortering
- [ ] Gruppera ihop områdena så att trädet blir mer överskådligt

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin Samma lösning som finns på terapirekommendationer är aktiverat på stage nu. Administratörer + Redaktörer har tillåtelse att ändra menyordningen genom att drag and drop och sen klicka på "Sync Sida Order" uppe till höger (Jag tänkte göra en pull request för att förbättra översättningarna 😄).
