### ISSUE TITLE
Som besökare vill jag bara ha ett rubrikfält 

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#87]
I dagsläget upprepar vi rubriken på 
1) Brödsmulorna
2) Det blå fältet med bakåtpilen som h1
3) I vita innehållsfältet som h1

Särskilt med lite längre rubriker ser det ganska udda ut med samma text staplad på sig självt tre gånger. Logiskt är det också knepigt att ha två likalydande h1:or. Jag föreslår att vi nöjer oss med brödsmulor + 1 rubrik. (Jag föreslår den vita då den blå visserligen är snygg men bakåtpilens funktion inte är uppenbar samtidigt som den blå plattan gör rubriken till något separat från innehållet på sidan.)

**Nuläge:** 
![hallandstematrubrikernulage](https://user-images.githubusercontent.com/3371823/39753195-3973d384-52be-11e8-83ef-ff5155eff5d8.png)

**Med bara vanlig rubrik i vitt fält:** 
![hallandstematrubrikervitrubrik](https://user-images.githubusercontent.com/3371823/39753217-452f9870-52be-11e8-9c4d-423070d68412.png)

**Med blå rubriken** 
![hallandstematrubrikerblarubrik](https://user-images.githubusercontent.com/3371823/39753225-4af7c890-52be-11e8-8a1b-7f409f911278.png)

# Acceptanskriterier

- [ ] Endast en h1

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
(Alla verkar överens om att det blå fältet skall bort på den här typen av sidor, men det påverkar såklart designen eftersom det då blir väldigt tomt och vitt)

**Comment by JohannaOlin** [comment]
Det blå fältet med bakåtpilen är borttaget från vanliga sidor nu så jag stänger storyn
