### ISSUE TITLE
Designen bryter till mobilläge väl tidigt - (Tidigare: vardgivare.regionhalland.se visar mobilnavigation ända upp till 1300px bredd)

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#89]
Ser ut som att vardgivare.regionhalland.se för närvarande visar mobilnavigationen ända upp till 1300px bredd. (Vi bör kanske kombinera skärmupplösning, skärmens pixeltäthet samt om skärmen är av liggande/stående orientering för att avgöra vad som är desktop/mobil.)

# Acceptanskriterier

- [ ] Beteendet från stage är tillbaka. 
- [ ] Allra helst: Högupplöst mobil får mobilnavigationen likväl som en lågupplöst laptop får desktopnavigationen. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
@fridabergentoft @marysjodin Efter lite resonerande så kom jag o David fram till att det är en fråga för er - är det ok att huvudnavigationen bryts till två rader för att undvika att visa mobilmenyn på desktop? Det är i slutänden där skon klämmer :) Jag har provat att visa den på två rader och tycker det ser ok ut, däremot behöver vi justera så att drop downen isf inte täcker den undre raden. 

Lagt den i sprint 0 istället och bytt tagg från bug till enhancement.

**Comment by JohannaOlin** [comment]
Då tar vi med denna i det arbetet som Linus, Maria och Frida ska göra vecka 24-25. Jag lägger denna på sprint 9 istället. Tanken är att skissande sker i sprint 8 och att utvecklingen då görs i sprint 9.

**Comment by JohannaOlin** [comment]
@regionhallandviktor När du är tillbaka från semestern så kan du titta på det nya skissförslaget där det inte finns någon toppnavigation på samma sätt längre. Kanske löser sig detta problem automatiskt då?

**Comment by regionhallandviktor** [comment]
Släcker denna då den rör gamla designen.
