### ISSUE TITLE
vardgivare.regionhalland.se öppnar menyn på hover och inte på klick

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#92]
vardgivare.regionhalland.se öppnar inte menyn på klick längre utan har backat till beteendet att öppna på hover. 

# Acceptanskriterier

- [x] Menyn öppnas på klick

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
Beror på felaktigheter på den gamla servern och löser sig i och med ompekningen.
