### ISSUE TITLE
Som besökare vill jag själv stänga öppna flikar i mobilnavigationen för att undvika att den scrollar på ett förvirrande sätt

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#94]
# user story
Som besökare vill jag inte att mobilnavigationen "scrollar fel" när jag öppnar en ny rubrik pga att andra rubriker stängs. 

# Beskrivning av problemet: 
När man öppnat någonting i mobilmenyn, scrollar ned och öppnar en underliggande rubrik fälls den första rubriken ihop varpå det nya innehåll man klickat på ibland försvinner ovanför skärmkanten. 

# Reproducera: 
1) Gå till vardgivare.regionhalland.se [11 maj 2018] och öppna "Behandlingsstöd" i mobilläget. 
2) Scrolla ned en bit och öppna "Service och IT" - nu väntar du dig att underrubrikerna skall visas. 
3) Notera att du inte du snarare ser "Uppdrag och samverkan" på nivå 1 eftersom innehållet scrollade upp då en lång lista fälldes ihop och ersattes av en kort. 

# Acceptanskriterier

- [ ] Användarna kan öppna nya rubriker utan att att den rubrik de klickade på försvinner utom synhåll. 

## Standard AC:s
- [ ] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [ ] Lösningen har kodgranskats av en kollega
- [ ] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [ ] Storyn har synkats med övriga produktägare
- [ ] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by regionhallandviktor** [comment]
(Förslagsvis så låter vi användarna själva stänga öppna rubriker för att undvika problem när rubriker ovanför den man klickade på fälls ihop och navigationen scrollas)

**Comment by JohannaOlin** [comment]
@fridabergentoft Vet inte om detta går att få med på skissen på den nya mobilnavigationen, men det är vettigt att vi låter besökarna själva stänga öppnade menyer. När besökaren i Viktors exempel öppnar Service och IT så är Behandlingsstöd fortfarande öppet.

Går det inte att få med på skissen så tar vi ärendet vidare direkt när vi bygger istället.

**Comment by JohannaOlin** [comment]
Lagd på omarbetningen issue 209 istället

**Comment by regionhallandviktor** [comment]
Så länge vi behåller bara en nivå i hamburgaren så kan vi släcka den här.
