### ISSUE TITLE
Som besökare vill jag att cookie-notisen inte mörkas ned när jag öppnar menyn

### ISSUE THREAD

**Issue by regionhallandviktor** [RegionHalland/halland#95]
I dagsläget mörkas cookie-notisen ned när man öppnar menyn vilket får den effekten att menyn ser ut att simma omkring i mitten av skärmen utan någon riktig förankring. 

# Acceptanskriterier

- [x] Cookie-notisen är synlig även när man har menyn öppen. 

![image.png](https://images.zenhubusercontent.com/5a81c2c04b5806bc2bc69a1a/690bc8d0-c2ee-4b15-8704-1d8fbfe3d95b)

## Standard AC:s
- [x] Lösningen fungerar på alla skärmar (mobil, tablet, pc)
- [x] Lösningen har kodgranskats av en kollega
- [x] Eventuellt nya komponenter har dokumenterats och syns på design.regionhalland.se
- [x] Storyn har synkats med övriga produktägare
- [x] Lösningen går i linje med WCAG 2.0 AA

# Övrig information

**Comment by davidohlin** [comment]
@JohannaOlin @regionhallandviktor Detta är på plats på stage nu, kika på stage i inkognito-läge.

**Comment by regionhallandviktor** [comment]
Testat i Chrome, Opera och Safari på desktop och Safari o Chrome på mobil (Android + iOS). Verkar funka som avsett.

**Comment by regionhallandviktor** [comment]
Samma med IE och Edge - inga problem. Jag är nöjd :)
